"""
Data preparation utilities for thesaurus LLM fine-tuning.
"""
import os
import json
import nltk
import pandas as pd
from nltk.corpus import wordnet as wn
from tqdm import tqdm

def download_nltk_resources():
    """Download required NLTK resources."""
    nltk.download('wordnet')
    nltk.download('omw-1.4')

def generate_thesaurus_data(output_file='thesaurus_data.json', num_words=5000):
    """
    Generate thesaurus training data from WordNet.
    
    Args:
        output_file (str): Path to save the generated data
        num_words (int): Number of words to include in the dataset
    
    Returns:
        list: The generated dataset
    """
    # Download required resources
    download_nltk_resources()
    
    # Get all English lemmas from WordNet
    all_lemmas = set()
    for synset in tqdm(list(wn.all_synsets()), desc="Collecting lemmas"):
        all_lemmas.update([lemma.name() for lemma in synset.lemmas() if '_' not in lemma.name()])
    
    # Convert to list and limit to specified number
    all_lemmas = list(all_lemmas)[:num_words]
    
    # Generate thesaurus entries
    thesaurus_data = []
    
    for word in tqdm(all_lemmas, desc="Generating thesaurus entries"):
        entry = {"word": word, "synonyms": [], "antonyms": [], "hypernyms": [], "hyponyms": []}
        
        # Get synsets for the word
        synsets = wn.synsets(word)
        
        for synset in synsets:
            # Get synonyms
            for lemma in synset.lemmas():
                if lemma.name() != word and '_' not in lemma.name():
                    entry["synonyms"].append(lemma.name())
                    
                # Get antonyms
                for antonym in lemma.antonyms():
                    if '_' not in antonym.name():
                        entry["antonyms"].append(antonym.name())
            
            # Get hypernyms (more general terms)
            for hypernym in synset.hypernyms():
                for lemma in hypernym.lemmas():
                    if '_' not in lemma.name():
                        entry["hypernyms"].append(lemma.name())
            
            # Get hyponyms (more specific terms)
            for hyponym in synset.hyponyms():
                for lemma in hyponym.lemmas():
                    if '_' not in lemma.name():
                        entry["hyponyms"].append(lemma.name())
        
        # Remove duplicates
        for key in entry:
            if key != "word":
                entry[key] = list(set(entry[key]))
        
        # Only add entries that have at least one synonym
        if entry["synonyms"]:
            thesaurus_data.append(entry)
    
    # Save to file
    with open(output_file, 'w') as f:
        json.dump(thesaurus_data, f, indent=2)
    
    print(f"Generated {len(thesaurus_data)} thesaurus entries")
    return thesaurus_data

def prepare_training_data(thesaurus_data, output_file='training_data.json'):
    """
    Convert thesaurus data to training examples for the LLM.
    
    Args:
        thesaurus_data (list): Thesaurus data generated by generate_thesaurus_data
        output_file (str): Path to save the training data
    
    Returns:
        list: The generated training examples
    """
    training_examples = []
    
    for entry in tqdm(thesaurus_data, desc="Preparing training examples"):
        word = entry["word"]
        
        # Create examples for synonyms
        if entry["synonyms"]:
            synonyms_str = ", ".join(entry["synonyms"])
            training_examples.append({
                "instruction": f"List synonyms for the word '{word}'.",
                "input": "",
                "output": f"Synonyms for '{word}': {synonyms_str}"
            })
            
            # Create examples for individual synonym lookups
            for synonym in entry["synonyms"][:3]:  # Limit to 3 examples per word
                training_examples.append({
                    "instruction": f"Is '{synonym}' a synonym of '{word}'?",
                    "input": "",
                    "output": f"Yes, '{synonym}' is a synonym of '{word}'."
                })
        
        # Create examples for antonyms
        if entry["antonyms"]:
            antonyms_str = ", ".join(entry["antonyms"])
            training_examples.append({
                "instruction": f"What are the antonyms of '{word}'?",
                "input": "",
                "output": f"Antonyms of '{word}': {antonyms_str}"
            })
        
        # Create examples for hypernyms and hyponyms
        if entry["hypernyms"]:
            hypernyms_str = ", ".join(entry["hypernyms"])
            training_examples.append({
                "instruction": f"What are more general terms (hypernyms) for '{word}'?",
                "input": "",
                "output": f"More general terms for '{word}': {hypernyms_str}"
            })
        
        if entry["hyponyms"]:
            hyponyms_str = ", ".join(entry["hyponyms"])
            training_examples.append({
                "instruction": f"What are more specific terms (hyponyms) for '{word}'?",
                "input": "",
                "output": f"More specific terms for '{word}': {hyponyms_str}"
            })
    
    # Save to file
    with open(output_file, 'w') as f:
        json.dump(training_examples, f, indent=2)
    
    print(f"Generated {len(training_examples)} training examples")
    return training_examples

if __name__ == "__main__":
    # Generate thesaurus data
    thesaurus_data = generate_thesaurus_data(num_words=1000)  # Reduced for testing
    
    # Prepare training data
    training_examples = prepare_training_data(thesaurus_data)
