"""
Visual Thesaurus Interface for the LLM Fine-Tuning Project.
This module provides visualization tools for displaying word relationships.
"""
import os
import json
import networkx as nx
import matplotlib.pyplot as plt
from pyvis.network import Network
import plotly.graph_objects as go
import nltk
from nltk.corpus import wordnet as wn
import pandas as pd
from IPython.display import HTML, display

class VisualThesaurus:
    """
    A class to create visual representations of word relationships.
    """

    def __init__(self, thesaurus_data=None):
        """
        Initialize the VisualThesaurus.

        Args:
            thesaurus_data (list, optional): Thesaurus data in the format generated by data_preparation.py
        """
        self.thesaurus_data = thesaurus_data
        self.graph = nx.Graph()

        # Download required NLTK resources if not already downloaded
        try:
            nltk.data.find('corpora/wordnet')
        except LookupError:
            nltk.download('wordnet')
            nltk.download('omw-1.4')

    def load_thesaurus_data(self, file_path):
        """
        Load thesaurus data from a JSON file.

        Args:
            file_path (str): Path to the thesaurus data JSON file
        """
        with open(file_path, 'r') as f:
            self.thesaurus_data = json.load(f)

    def build_graph_for_word(self, word, max_depth=1, relation_types=None):
        """
        Build a graph for a specific word and its relationships.

        Args:
            word (str): The central word to visualize
            max_depth (int): How many levels of relationships to include
            relation_types (list): Types of relationships to include ('synonyms', 'antonyms', 'hypernyms', 'hyponyms')

        Returns:
            networkx.Graph: The constructed graph
        """
        if relation_types is None:
            relation_types = ['synonyms', 'antonyms', 'hypernyms', 'hyponyms']

        # Create a new graph
        self.graph = nx.Graph()

        # Add the central word
        self.graph.add_node(word, size=25, color='red', label=word)

        # Get synsets for the word
        synsets = wn.synsets(word)

        # Function to add related words to the graph
        def add_related_words(source_word, current_depth=0):
            if current_depth >= max_depth:
                return

            for synset in wn.synsets(source_word):
                # Add synonyms
                if 'synonyms' in relation_types:
                    for lemma in synset.lemmas():
                        if lemma.name() != source_word and '_' not in lemma.name():
                            related_word = lemma.name()
                            if not self.graph.has_node(related_word):
                                self.graph.add_node(related_word, size=15, color='blue', label=related_word)
                            if not self.graph.has_edge(source_word, related_word):
                                self.graph.add_edge(source_word, related_word, color='blue', label='synonym')

                            # Recursively add related words
                            if current_depth < max_depth - 1:
                                add_related_words(related_word, current_depth + 1)

                # Add antonyms
                if 'antonyms' in relation_types:
                    for lemma in synset.lemmas():
                        for antonym in lemma.antonyms():
                            if '_' not in antonym.name():
                                related_word = antonym.name()
                                if not self.graph.has_node(related_word):
                                    self.graph.add_node(related_word, size=15, color='orange', label=related_word)
                                if not self.graph.has_edge(source_word, related_word):
                                    self.graph.add_edge(source_word, related_word, color='orange', label='antonym')

                # Add hypernyms (more general terms)
                if 'hypernyms' in relation_types:
                    for hypernym in synset.hypernyms():
                        for lemma in hypernym.lemmas():
                            if '_' not in lemma.name():
                                related_word = lemma.name()
                                if not self.graph.has_node(related_word):
                                    self.graph.add_node(related_word, size=15, color='green', label=related_word)
                                if not self.graph.has_edge(source_word, related_word):
                                    self.graph.add_edge(source_word, related_word, color='green', label='hypernym')

                # Add hyponyms (more specific terms)
                if 'hyponyms' in relation_types:
                    for hyponym in synset.hyponyms():
                        for lemma in hyponym.lemmas():
                            if '_' not in lemma.name():
                                related_word = lemma.name()
                                if not self.graph.has_node(related_word):
                                    self.graph.add_node(related_word, size=15, color='purple', label=related_word)
                                if not self.graph.has_edge(source_word, related_word):
                                    self.graph.add_edge(source_word, related_word, color='purple', label='hyponym')

        # Build the graph
        add_related_words(word)

        return self.graph

    def visualize_matplotlib(self, word=None, figsize=(12, 12), save_path=None):
        """
        Visualize the thesaurus graph using matplotlib.

        Args:
            word (str, optional): Word to visualize. If None, uses the existing graph.
            figsize (tuple): Figure size
            save_path (str, optional): Path to save the visualization

        Returns:
            matplotlib.figure.Figure: The figure object
        """
        if word:
            self.build_graph_for_word(word)

        if not self.graph.nodes():
            raise ValueError("Graph is empty. Please build a graph first.")

        # Create a figure
        plt.figure(figsize=figsize)

        # Get node colors and sizes
        node_colors = [self.graph.nodes[node].get('color', 'blue') for node in self.graph.nodes()]
        node_sizes = [self.graph.nodes[node].get('size', 300) for node in self.graph.nodes()]

        # Get edge colors
        edge_colors = [self.graph.edges[edge].get('color', 'gray') for edge in self.graph.edges()]

        # Create a layout for the graph
        pos = nx.spring_layout(self.graph, seed=42)

        # Draw the graph
        nx.draw_networkx_nodes(self.graph, pos, node_color=node_colors, node_size=node_sizes, alpha=0.8)
        nx.draw_networkx_edges(self.graph, pos, edge_color=edge_colors, width=1.5, alpha=0.7)
        nx.draw_networkx_labels(self.graph, pos, font_size=10, font_family='sans-serif')

        plt.axis('off')
        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, format='png', dpi=300, bbox_inches='tight')

        return plt.gcf()

    def _visualize_large_graph(self, word, height='500px', width='100%', save_path=None):
        """
        Simplified visualization for large graphs.

        Args:
            word (str): The word being visualized
            height (str): Height of the visualization
            width (str): Width of the visualization
            save_path (str): Path to save the HTML file

        Returns:
            IPython.display.HTML: HTML display object
        """
        # Create a simplified visualization using matplotlib
        plt.figure(figsize=(12, 12))

        # Use a more efficient layout algorithm for large graphs
        pos = nx.spring_layout(self.graph, k=0.3, iterations=50, seed=42)

        # Draw nodes with minimal styling
        nx.draw_networkx_nodes(
            self.graph, pos,
            node_size=100,
            node_color='skyblue',
            alpha=0.8
        )

        # Draw edges with minimal styling
        nx.draw_networkx_edges(
            self.graph, pos,
            width=0.5,
            alpha=0.5,
            edge_color='gray'
        )

        # Draw labels for only the most important nodes
        # Find the top 20 nodes by degree
        top_nodes = sorted(self.graph.degree, key=lambda x: x[1], reverse=True)[:20]
        top_node_dict = {n: pos[n] for n, _ in top_nodes}

        nx.draw_networkx_labels(
            self.graph, top_node_dict,
            font_size=10,
            font_family='sans-serif'
        )

        plt.axis('off')
        plt.tight_layout()

        # Save to a temporary file
        if save_path:
            temp_img_path = save_path.replace('.html', '.png')
        else:
            temp_img_path = f"static/visualizations/{word}_large_graph.png"

        plt.savefig(temp_img_path, format='png', dpi=300, bbox_inches='tight')
        plt.close()

        # Create a simple HTML file that displays the image
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Large Graph Visualization for {word}</title>
    <style>
        body, html {{
            height: 100%;
            margin: 0;
            padding: 0;
            background-color: #121212;
            color: white;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }}
        .container {{
            text-align: center;
            max-width: 1000px;
            padding: 20px;
        }}
        h1 {{
            margin-bottom: 20px;
        }}
        .graph-image {{
            max-width: 100%;
            height: auto;
            border-radius: 10px;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.5);
        }}
        .info {{
            margin-top: 20px;
            padding: 15px;
            background-color: rgba(0, 0, 0, 0.3);
            border-radius: 10px;
            max-width: 600px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Large Graph Visualization for "{word}"</h1>
        <div class="info">
            <p>This graph contains {len(self.graph.nodes())} nodes and {len(self.graph.edges())} connections.</p>
            <p>A simplified static visualization is shown due to the large size of the graph.</p>
        </div>
        <img src="/{temp_img_path}" alt="Graph visualization for {word}" class="graph-image">
    </div>
</body>
</html>"""

        # Save the HTML file
        if save_path:
            with open(save_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            return HTML(f'<iframe src="{save_path}" height="{height}" width="{width}" style="border: none; background-color: #121212;"></iframe>')
        else:
            temp_html_path = f"static/visualizations/{word}_large_graph.html"
            with open(temp_html_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            return HTML(f'<iframe src="{temp_html_path}" height="{height}" width="{width}" style="border: none; background-color: #121212;"></iframe>')

    def visualize_interactive(self, word=None, height='500px', width='100%', save_path=None):
        """
        Create an interactive visualization using pyvis.

        Args:
            word (str, optional): Word to visualize. If None, uses the existing graph.
            height (str): Height of the visualization
            width (str): Width of the visualization
            save_path (str, optional): Path to save the HTML file

        Returns:
            IPython.display.HTML: HTML display object
        """
        # Error HTML template for fallback
        error_html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualization Error</title>
    <style>
        body, html {
            height: 100%;
            margin: 0;
            padding: 0;
            background-color: #121212;
            color: white;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }
        .error-container {
            text-align: center;
            max-width: 600px;
            padding: 30px;
            background-color: rgba(255, 0, 0, 0.1);
            border-radius: 10px;
            border: 1px solid rgba(255, 0, 0, 0.3);
        }
        h1 {
            color: #ff5555;
        }
        .error-details {
            margin-top: 20px;
            padding: 15px;
            background-color: rgba(0, 0, 0, 0.3);
            border-radius: 5px;
            text-align: left;
            font-family: monospace;
            white-space: pre-wrap;
            word-break: break-all;
        }
    </style>
</head>
<body>
    <div class="error-container">
        <h1>Visualization Error</h1>
        <p>An error occurred while generating the visualization:</p>
        <div class="error-details">ERROR_MESSAGE</div>
        <p>Try with a different word or a smaller graph size.</p>
    </div>
</body>
</html>"""

        try:
            # Build graph if word is provided
            if word:
                try:
                    self.build_graph_for_word(word)
                except Exception as e:
                    print(f"Warning: Error building graph for '{word}': {e}")
                    # If graph building fails, create a minimal graph with just the word
                    self.graph = nx.Graph()
                    self.graph.add_node(word, size=25, color='red', label=word)

            # Check if graph is empty
            if not self.graph.nodes():
                print("Warning: Graph is empty. Creating a minimal graph.")
                # Create a minimal graph with a placeholder node
                self.graph.add_node("No data available", size=25, color='red', label="No data available")

            # Determine graph size for adaptive visualization
            graph_size = len(self.graph.nodes())
            print(f"Graph size: {graph_size} nodes")

            # Use different visualization approaches based on graph size
            if graph_size > 100:
                # For very large graphs, simplify the visualization
                print("Using simplified visualization for large graph")
                return self._visualize_large_graph(word, height, width, save_path)

            # Create a pyvis network with error handling
            try:
                net = Network(height=height, width=width, notebook=True, directed=False)
            except Exception as e:
                print(f"Error creating Network: {e}")
                # Fallback to a simpler network configuration
                net = Network(height=height, width=width, notebook=True)

            # Add nodes and edges from the networkx graph with error handling
            for node in self.graph.nodes():
                try:
                    # Get the definition for the node if available
                    definition = ""
                    try:
                        synsets = wn.synsets(node)
                        if synsets:
                            definition = synsets[0].definition()
                    except Exception as e:
                        print(f"Warning: Error getting definition for '{node}': {e}")

                    # Create a tooltip with the definition
                    tooltip = f"<div style='max-width:300px;'><b>{node}</b><br/>{definition}</div>"

                    # Get node attributes with fallbacks
                    label = self.graph.nodes[node].get('label', str(node))
                    color = self.graph.nodes[node].get('color', 'blue')
                    size = self.graph.nodes[node].get('size', 25)

                    # Add node to network
                    net.add_node(
                        node,
                        label=label,
                        color=color,
                        size=size,
                        title=tooltip,
                        font={'size': 16, 'face': 'Arial'}
                    )
                except Exception as e:
                    print(f"Warning: Error adding node '{node}': {e}")
                    # Add a simplified node as fallback
                    try:
                        net.add_node(str(node), label=str(node), color='gray', size=15)
                    except:
                        # If all else fails, skip this node
                        continue

            # Add edges with error handling
            for edge in self.graph.edges():
                try:
                    source, target = edge
                    # Check if both nodes exist in the network
                    if source in net.nodes and target in net.nodes:
                        color = self.graph.edges[edge].get('color', 'gray')
                        title = self.graph.edges[edge].get('label', '')
                        net.add_edge(source, target, color=color, title=title, width=2)
                except Exception as e:
                    print(f"Warning: Error adding edge {edge}: {e}")
                    # Skip this edge if there's an error

            # Adjust physics settings based on graph size
            gravity = -30000
            central_gravity = 0.5
            spring_length = 200
            spring_strength = 0.05
            damping = 0.15
            iterations = 200

            if graph_size > 50:
                # For larger graphs, use more restrictive physics
                gravity = -15000
                central_gravity = 0.8
                spring_length = 120
                spring_strength = 0.08
                damping = 0.2
                iterations = 100
            elif graph_size > 30:
                # For medium graphs, use moderate physics
                gravity = -20000
                central_gravity = 0.6
                spring_length = 150
                spring_strength = 0.06
                damping = 0.18
                iterations = 150

            # Set physics layout with error handling
            try:
                net.barnes_hut(
                    gravity=gravity,
                    central_gravity=central_gravity,
                    spring_length=spring_length,
                    spring_strength=spring_strength,
                    damping=damping,
                    overlap=0.2
                )
            except Exception as e:
                print(f"Warning: Error setting physics: {e}")
                # Use default physics as fallback

            # Add enhanced zoom options and other interactive features
            options = {
                "interaction": {
                    "hover": True,
                    "zoomView": True,
                    "dragView": True,
                    "navigationButtons": True,
                    "keyboard": {
                        "enabled": True,
                        "speed": {
                            "x": 10,
                            "y": 10,
                            "zoom": 0.1
                        },
                        "bindToWindow": False  # Only respond when iframe is focused
                    },
                    "tooltipDelay": 100,
                    "multiselect": True,  # Allow selecting multiple nodes
                    "selectable": True,
                    "selectConnectedEdges": True,
                    "hoverConnectedEdges": True,
                    "zoomSpeed": 0.8  # Slower zoom for more control
                },
                "physics": {
                    "stabilization": {
                        "enabled": True,
                        "iterations": iterations,
                        "updateInterval": 50,
                        "onlyDynamicEdges": False,
                        "fit": True  # This helps fill the container
                    },
                    "adaptiveTimestep": True,  # Adaptive timestep for smoother physics
                    "maxVelocity": 30,  # Limit maximum velocity for stability
                    "minVelocity": 0.75,  # Higher minimum velocity threshold for stabilization
                    "solver": "barnesHut",
                    "timestep": 0.5,  # Smaller timestep for more stability
                    "wind": { "x": 0, "y": 0 }  # No wind force
                },
                "layout": {
                    "improvedLayout": True,
                    "randomSeed": 42  # Consistent layout between page loads
                }
            }

            try:
                net.set_options(json.dumps(options))
            except Exception as e:
                print(f"Warning: Error setting options: {e}")
                # Continue without custom options if there's an error

            # Try to use the enhanced template first
            template_path = 'static/visualizations/enhanced_template.html'
            html_template = ""
            try:
                with open(template_path, 'r', encoding='utf-8') as f:
                    html_template = f.read()
                print(f"Using enhanced template: {template_path}")
            except FileNotFoundError:
                # Fall back to standard template
                template_path = 'static/visualizations/template.html'
                try:
                    with open(template_path, 'r', encoding='utf-8') as f:
                        html_template = f.read()
                    print(f"Using standard template: {template_path}")
                except FileNotFoundError:
                    # Fallback to embedded template if file not found
                    print("Using embedded template as fallback")
                    html_template = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thesaurus Visualization</title>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vis-network@9.1.2/dist/vis-network.min.js"></script>
    <style type="text/css">
        #mynetwork {
            width: 100%;
            height: 100%;
            position: absolute;
            top: 0;
            left: 0;
            border: none;
            background-color: #1e1e1e; /* Dark background */
        }
        body, html {
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        .vis-tooltip {
            position: absolute;
            visibility: hidden;
            padding: 10px 15px;
            white-space: nowrap;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 14px;
            color: #ffffff;
            background-color: rgba(0, 0, 0, 0.8);
            border-radius: 8px;
            border: 1px solid rgba(255, 255, 255, 0.2);
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
            max-width: 300px;
            word-wrap: break-word;
            z-index: 900;
            -webkit-backdrop-filter: blur(5px);
            backdrop-filter: blur(5px);
        }
    </style>
</head>
<body>
    <div id="mynetwork"></div>
    <script type="text/javascript">
        // Initialize the network
        var container = document.getElementById('mynetwork');
        var data = REPLACE_WITH_DATA;
        var options = {
            nodes: {
                font: {
                    color: '#ffffff',
                    size: 16,
                    face: 'Segoe UI, Tahoma, Geneva, Verdana, sans-serif',
                    strokeWidth: 3,
                    strokeColor: '#1e1e1e'
                },
                borderWidth: 2,
                borderWidthSelected: 4,
                shadow: true
            },
            edges: {
                width: 2,
                selectionWidth: 4,
                smooth: {
                    type: 'dynamic',
                    forceDirection: 'none',
                    roundness: 0.5
                },
                shadow: true,
                color: {
                    inherit: false,
                    opacity: 0.8
                }
            },
            physics: {
                stabilization: {
                    enabled: true,
                    iterations: 200,
                    updateInterval: 50,
                    fit: true
                },
                barnesHut: {
                    gravitationalConstant: -30000,
                    centralGravity: 0.5,
                    springLength: 200,
                    springConstant: 0.05,
                    damping: 0.15,
                    avoidOverlap: 0.2
                }
            },
            interaction: {
                hover: true,
                zoomView: true,
                dragView: true,
                navigationButtons: true
            }
        };
        var network = new vis.Network(container, data, options);

        // Add click event to nodes
        network.on("click", function(params) {
            if (params.nodes.length > 0) {
                var nodeId = params.nodes[0];
                if (nodeId !== '') {
                    try {
                        window.parent.location.href = '/visualize/' + encodeURIComponent(nodeId);
                    } catch (e) {
                        console.error('Error navigating to node:', e);
                        window.location.href = '/visualize/' + encodeURIComponent(nodeId);
                    }
                }
            }
        });
    </script>
</body>
</html>"""

            # Replace placeholders with actual data
            nodes_data = []
            for node in self.graph.nodes():
                # Get the definition for the node if available
                definition = ""
                try:
                    synsets = wn.synsets(node)
                    if synsets:
                        definition = synsets[0].definition()
                except Exception as e:
                    print(f"Warning: Error getting definition for '{node}': {e}")

                nodes_data.append({
                    'id': node,
                    'label': self.graph.nodes[node].get('label', node),
                    'color': self.graph.nodes[node].get('color', '#97c2fc'),
                    'size': self.graph.nodes[node].get('size', 25),
                    'title': f"<div style='max-width:300px;'><b>{node}</b><br/>{definition}</div>"
                })

            edges_data = []
            for edge in self.graph.edges():
                edge_label = self.graph.edges[edge].get('label', '')
                edges_data.append({
                    'from': edge[0],
                    'to': edge[1],
                    'color': self.graph.edges[edge].get('color', '#848484'),
                    'width': 2,
                    'title': edge_label
                })

            network_data = json.dumps({
                "nodes": nodes_data,
                "edges": edges_data
            })

            # Replace the placeholder in the template with the actual data
            html_content = html_template.replace("REPLACE_WITH_DATA", network_data)

            # Save the HTML file
            if save_path:
                with open(save_path, 'w', encoding='utf-8') as f:
                    f.write(html_content)
                return HTML(f'<iframe src="{save_path}" height="{height}" width="{width}" style="border: none; background-color: #121212;"></iframe>')
            else:
                temp_path = "thesaurus_visualization.html"
                with open(temp_path, 'w', encoding='utf-8') as f:
                    f.write(html_content)
                return HTML(f'<iframe src="{temp_path}" height="{height}" width="{width}" style="border: none; background-color: #121212;"></iframe>')

        except Exception as e:
            # Handle any unexpected errors
            print(f"Error in visualization: {e}")
            # Create a simple error message HTML
            error_content = error_html.replace("ERROR_MESSAGE", str(e))
            # Save the error HTML
            error_path = "thesaurus_visualization_error.html"
            with open(error_path, 'w', encoding='utf-8') as f:
                f.write(error_content)
            return HTML(f'<iframe src="{error_path}" height="{height}" width="{width}" style="border: none; background-color: #121212;"></iframe>')

    def visualize_plotly(self, word=None, height=600, width=900):
        """
        Create an interactive visualization using Plotly.

        Args:
            word (str, optional): Word to visualize. If None, uses the existing graph.
            height (int): Height of the visualization
            width (int): Width of the visualization

        Returns:
            plotly.graph_objects.Figure: Plotly figure object
        """
        if word:
            self.build_graph_for_word(word)

        if not self.graph.nodes():
            raise ValueError("Graph is empty. Please build a graph first.")

        # Create a layout for the graph
        pos = nx.spring_layout(self.graph, seed=42)

        # Create edge traces
        edge_traces = []

        for edge in self.graph.edges():
            x0, y0 = pos[edge[0]]
            x1, y1 = pos[edge[1]]

            edge_color = self.graph.edges[edge].get('color', 'gray')
            edge_label = self.graph.edges[edge].get('label', '')

            edge_trace = go.Scatter(
                x=[x0, x1, None],
                y=[y0, y1, None],
                line=dict(width=1.5, color=edge_color),
                hoverinfo='none',
                mode='lines',
                name=edge_label
            )

            edge_traces.append(edge_trace)

        # Create node trace
        node_trace = go.Scatter(
            x=[pos[node][0] for node in self.graph.nodes()],
            y=[pos[node][1] for node in self.graph.nodes()],
            mode='markers+text',
            text=[node for node in self.graph.nodes()],
            textposition='top center',
            hoverinfo='text',
            marker=dict(
                showscale=False,
                color=[self.graph.nodes[node].get('color', 'blue') for node in self.graph.nodes()],
                size=[self.graph.nodes[node].get('size', 15) for node in self.graph.nodes()],
                line=dict(width=2, color='white')
            )
        )

        # Create figure
        fig = go.Figure(
            data=edge_traces + [node_trace],
            layout=go.Layout(
                title=f'Visual Thesaurus for "{word}"' if word else 'Visual Thesaurus',
                showlegend=False,
                hovermode='closest',
                margin=dict(b=20, l=5, r=5, t=40),
                xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
                yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
                height=height,
                width=width
            )
        )

        return fig

    def create_web_visualization(self, word, output_dir='web_visualizations'):
        """
        Create a standalone HTML visualization for web display.

        Args:
            word (str): Word to visualize
            output_dir (str): Directory to save the visualization

        Returns:
            str: Path to the generated HTML file
        """
        # Create output directory if it doesn't exist
        os.makedirs(output_dir, exist_ok=True)

        # Build the graph
        self.build_graph_for_word(word)

        # Create the visualization
        output_path = os.path.join(output_dir, f'{word}_thesaurus.html')
        self.visualize_interactive(save_path=output_path)

        return output_path

# Example usage
if __name__ == "__main__":
    # Create a visual thesaurus
    visual_thesaurus = VisualThesaurus()

    # Visualize a word
    word = "happy"
    visual_thesaurus.build_graph_for_word(word)

    # Create and display visualizations
    visual_thesaurus.visualize_matplotlib(save_path=f"{word}_thesaurus.png")
    visual_thesaurus.visualize_interactive(save_path=f"{word}_thesaurus.html")

    print(f"Visualizations created for '{word}'")
