"""
Visual Thesaurus Interface for the LLM Fine-Tuning Project.
This module provides visualization tools for displaying word relationships.
"""
import os
import json
import networkx as nx
import matplotlib.pyplot as plt
from pyvis.network import Network
import plotly.graph_objects as go
import nltk
from nltk.corpus import wordnet as wn
import pandas as pd
from IPython.display import HTML, display

class VisualThesaurus:
    """
    A class to create visual representations of word relationships.
    """

    def __init__(self, thesaurus_data=None):
        """
        Initialize the VisualThesaurus.

        Args:
            thesaurus_data (list, optional): Thesaurus data in the format generated by data_preparation.py
        """
        self.thesaurus_data = thesaurus_data
        self.graph = nx.Graph()

        # Download required NLTK resources if not already downloaded
        try:
            nltk.data.find('corpora/wordnet')
        except LookupError:
            nltk.download('wordnet')
            nltk.download('omw-1.4')

    def load_thesaurus_data(self, file_path):
        """
        Load thesaurus data from a JSON file.

        Args:
            file_path (str): Path to the thesaurus data JSON file
        """
        with open(file_path, 'r') as f:
            self.thesaurus_data = json.load(f)

    def build_graph_for_word(self, word, max_depth=1, relation_types=None):
        """
        Build a graph for a specific word and its relationships.

        Args:
            word (str): The central word to visualize
            max_depth (int): How many levels of relationships to include
            relation_types (list): Types of relationships to include ('synonyms', 'antonyms', 'hypernyms', 'hyponyms')

        Returns:
            networkx.Graph: The constructed graph
        """
        if relation_types is None:
            relation_types = ['synonyms', 'antonyms', 'hypernyms', 'hyponyms']

        # Create a new graph
        self.graph = nx.Graph()

        # Add the central word
        self.graph.add_node(word, size=25, color='red', label=word)

        # Get synsets for the word
        synsets = wn.synsets(word)

        # Function to add related words to the graph
        def add_related_words(source_word, current_depth=0):
            if current_depth >= max_depth:
                return

            for synset in wn.synsets(source_word):
                # Add synonyms
                if 'synonyms' in relation_types:
                    for lemma in synset.lemmas():
                        if lemma.name() != source_word and '_' not in lemma.name():
                            related_word = lemma.name()
                            if not self.graph.has_node(related_word):
                                self.graph.add_node(related_word, size=15, color='blue', label=related_word)
                            if not self.graph.has_edge(source_word, related_word):
                                self.graph.add_edge(source_word, related_word, color='blue', label='synonym')

                            # Recursively add related words
                            if current_depth < max_depth - 1:
                                add_related_words(related_word, current_depth + 1)

                # Add antonyms
                if 'antonyms' in relation_types:
                    for lemma in synset.lemmas():
                        for antonym in lemma.antonyms():
                            if '_' not in antonym.name():
                                related_word = antonym.name()
                                if not self.graph.has_node(related_word):
                                    self.graph.add_node(related_word, size=15, color='orange', label=related_word)
                                if not self.graph.has_edge(source_word, related_word):
                                    self.graph.add_edge(source_word, related_word, color='orange', label='antonym')

                # Add hypernyms (more general terms)
                if 'hypernyms' in relation_types:
                    for hypernym in synset.hypernyms():
                        for lemma in hypernym.lemmas():
                            if '_' not in lemma.name():
                                related_word = lemma.name()
                                if not self.graph.has_node(related_word):
                                    self.graph.add_node(related_word, size=15, color='green', label=related_word)
                                if not self.graph.has_edge(source_word, related_word):
                                    self.graph.add_edge(source_word, related_word, color='green', label='hypernym')

                # Add hyponyms (more specific terms)
                if 'hyponyms' in relation_types:
                    for hyponym in synset.hyponyms():
                        for lemma in hyponym.lemmas():
                            if '_' not in lemma.name():
                                related_word = lemma.name()
                                if not self.graph.has_node(related_word):
                                    self.graph.add_node(related_word, size=15, color='purple', label=related_word)
                                if not self.graph.has_edge(source_word, related_word):
                                    self.graph.add_edge(source_word, related_word, color='purple', label='hyponym')

        # Build the graph
        add_related_words(word)

        return self.graph

    def visualize_matplotlib(self, word=None, figsize=(12, 12), save_path=None):
        """
        Visualize the thesaurus graph using matplotlib.

        Args:
            word (str, optional): Word to visualize. If None, uses the existing graph.
            figsize (tuple): Figure size
            save_path (str, optional): Path to save the visualization

        Returns:
            matplotlib.figure.Figure: The figure object
        """
        if word:
            self.build_graph_for_word(word)

        if not self.graph.nodes():
            raise ValueError("Graph is empty. Please build a graph first.")

        # Create a figure
        plt.figure(figsize=figsize)

        # Get node colors and sizes
        node_colors = [self.graph.nodes[node].get('color', 'blue') for node in self.graph.nodes()]
        node_sizes = [self.graph.nodes[node].get('size', 300) for node in self.graph.nodes()]

        # Get edge colors
        edge_colors = [self.graph.edges[edge].get('color', 'gray') for edge in self.graph.edges()]

        # Create a layout for the graph
        pos = nx.spring_layout(self.graph, seed=42)

        # Draw the graph
        nx.draw_networkx_nodes(self.graph, pos, node_color=node_colors, node_size=node_sizes, alpha=0.8)
        nx.draw_networkx_edges(self.graph, pos, edge_color=edge_colors, width=1.5, alpha=0.7)
        nx.draw_networkx_labels(self.graph, pos, font_size=10, font_family='sans-serif')

        plt.axis('off')
        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, format='png', dpi=300, bbox_inches='tight')

        return plt.gcf()

    def visualize_interactive(self, word=None, height='500px', width='100%', save_path=None):
        """
        Create an interactive visualization using pyvis.

        Args:
            word (str, optional): Word to visualize. If None, uses the existing graph.
            height (str): Height of the visualization
            width (str): Width of the visualization
            save_path (str, optional): Path to save the HTML file

        Returns:
            IPython.display.HTML: HTML display object
        """
        if word:
            self.build_graph_for_word(word)

        if not self.graph.nodes():
            raise ValueError("Graph is empty. Please build a graph first.")

        # Create a pyvis network
        net = Network(height=height, width=width, notebook=True, directed=False)

        # Add nodes and edges from the networkx graph
        for node in self.graph.nodes():
            # Get the definition for the node if available
            definition = ""
            synsets = wn.synsets(node)
            if synsets:
                definition = synsets[0].definition()

            # Create a tooltip with the definition
            tooltip = f"<div style='max-width:300px;'><b>{node}</b><br/>{definition}</div>"

            net.add_node(
                node,
                label=self.graph.nodes[node].get('label', node),
                color=self.graph.nodes[node].get('color', 'blue'),
                size=self.graph.nodes[node].get('size', 25),
                title=tooltip,
                font={'size': 16, 'face': 'Arial'}
            )

        for edge in self.graph.edges():
            net.add_edge(
                edge[0],
                edge[1],
                color=self.graph.edges[edge].get('color', 'gray'),
                title=self.graph.edges[edge].get('label', ''),
                width=2
            )

        # Set physics layout for better filling of the screen
        net.barnes_hut(
            gravity=-80000,
            central_gravity=0.3,
            spring_length=250,
            spring_strength=0.01,
            damping=0.09,
            overlap=0.1
        )

        # Add zoom options and other interactive features
        options = {
            "interaction": {
                "hover": True,
                "zoomView": True,
                "dragView": True,
                "navigationButtons": True,
                "keyboard": True,
                "tooltipDelay": 100
            },
            "physics": {
                "stabilization": {
                    "iterations": 100,
                    "fit": True  # This helps fill the container
                }
            },
            "layout": {
                "improvedLayout": True
            }
        }
        net.set_options(json.dumps(options))

        # Read the template file
        template_path = 'static/visualizations/template.html'
        try:
            with open(template_path, 'r', encoding='utf-8') as f:
                html_template = f.read()
        except FileNotFoundError:
            # Fallback to embedded template if file not found
            html_template = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thesaurus Visualization</title>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vis-network@9.1.2/dist/vis-network.min.js"></script>
    <style type="text/css">
        #mynetwork {
            width: 100%;
            height: 100%;
            position: absolute;
            top: 0;
            left: 0;
            border: none;
            background-color: #1e1e1e; /* Dark background */
        }
        body, html {
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        .vis-tooltip {
            position: absolute;
            visibility: hidden;
            padding: 10px 15px;
            white-space: nowrap;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 14px;
            color: #ffffff;
            background-color: rgba(0, 0, 0, 0.8);
            border-radius: 8px;
            border: 1px solid rgba(255, 255, 255, 0.2);
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
            max-width: 300px;
            word-wrap: break-word;
            z-index: 900;
            -webkit-backdrop-filter: blur(5px);
            backdrop-filter: blur(5px);
        }

        /* Custom node styling */
        .vis-network .vis-node {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-weight: 600;
            text-shadow: 0 1px 3px rgba(0, 0, 0, 0.5);
        }

        /* Controls styling */
        .vis-navigation {
            background-color: rgba(30, 30, 30, 0.7) !important;
            border-radius: 8px !important;
            border: 1px solid rgba(255, 255, 255, 0.1) !important;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3) !important;
            -webkit-backdrop-filter: blur(5px) !important;
            backdrop-filter: blur(5px) !important;
        }

        .vis-button {
            background-color: rgba(255, 255, 255, 0.1) !important;
            border: 1px solid rgba(255, 255, 255, 0.2) !important;
            border-radius: 4px !important;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2) !important;
            transition: all 0.3s ease !important;
        }

        .vis-button:hover {
            background-color: rgba(255, 255, 255, 0.2) !important;
            transform: translateY(-2px) !important;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3) !important;
        }

        .vis-button:active {
            transform: translateY(1px) !important;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2) !important;
        }
    </style>
</head>
<body>
    <div id="mynetwork"></div>
    <script type="text/javascript">
        // Initialize the network
        var container = document.getElementById('mynetwork');

        // Define custom node colors for dark theme
        const nodeColors = {
            main: "#ff4d4d",      // Bright red for main node
            synonym: "#ffcc00",   // Bright gold/yellow for synonyms
            related: "#00ffcc"    // Bright teal for related terms
        };

        // Define custom edge colors
        const edgeColors = {
            synonym: "#ffcc00",   // Bright gold/yellow for synonym connections
            related: "#00ffcc"    // Bright teal for related connections
        };

        // Process the data to use our custom colors
        var rawData = REPLACE_WITH_DATA;

        // Update node colors for better visibility on dark background
        rawData.nodes.forEach(node => {
            if (node.color === "red") {
                node.color = nodeColors.main;
            } else if (node.color === "blue") {
                node.color = nodeColors.synonym;
            } else if (node.color === "green") {
                node.color = nodeColors.related;
            }

            // Add shadow to nodes
            node.shadow = {
                enabled: true,
                color: node.color,
                size: 10,
                x: 0,
                y: 0
            };

            // Update tooltip styling
            if (node.title) {
                node.title = node.title.replace('<div style=\\'max-width:300px;\\'>', '<div style=\\'max-width:300px; color:#ffffff; font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;\\'>');
            }
        });

        // Update edge colors
        rawData.edges.forEach(edge => {
            if (edge.color === "blue") {
                edge.color = edgeColors.synonym;
            } else if (edge.color === "green") {
                edge.color = edgeColors.related;
            }

            // Add smooth curves to edges
            edge.smooth = {
                type: 'dynamic',
                roundness: 0.5
            };
        });

        var data = rawData;

        var options = {
            nodes: {
                font: {
                    color: '#ffffff',
                    size: 16,
                    face: 'Segoe UI',
                    strokeWidth: 3,
                    strokeColor: '#1e1e1e'
                },
                borderWidth: 2,
                borderWidthSelected: 4,
                shadow: true
            },
            edges: {
                width: 3,
                selectionWidth: 6,
                smooth: true,
                shadow: true,
                color: {
                    inherit: false,
                    opacity: 0.8
                },
                font: {
                    color: '#ffffff',
                    size: 14,
                    face: 'Segoe UI',
                    strokeWidth: 3,
                    strokeColor: '#1e1e1e',
                    background: 'rgba(30, 30, 30, 0.7)'
                }
            },
            interaction: {
                hover: true,
                zoomView: true,
                dragView: true,
                navigationButtons: true,
                keyboard: true,
                tooltipDelay: 100
            },
            physics: {
                stabilization: {
                    iterations: 100,
                    fit: true
                },
                barnesHut: {
                    gravitationalConstant: -5000,
                    centralGravity: 0.3,
                    springLength: 150,
                    springConstant: 0.04,
                    damping: 0.09
                }
            },
            layout: {
                improvedLayout: true,
                randomSeed: 42
            }
        };

        var network = new vis.Network(container, data, options);

        // Make the network object globally accessible
        window.network = network;

        // Fit the network to the container on load
        network.once("afterDrawing", function() {
            setTimeout(function() {
                network.fit({
                    animation: {
                        duration: 1000,
                        easingFunction: 'easeInOutQuad'
                    }
                });
            }, 200);
        });

        // Add click event to nodes
        network.on("click", function(params) {
            if (params.nodes.length > 0) {
                var nodeId = params.nodes[0];
                if (nodeId !== '') {
                    window.parent.location.href = '/visualize/' + encodeURIComponent(nodeId);
                }
            }
        });

        // Prevent errors when iframe is reloaded
        window.addEventListener('unload', function() {
            if (network) {
                try {
                    network.destroy();
                } catch (e) {
                    console.log('Network already destroyed');
                }
            }
        });
    </script>
</body>
</html>"""

        # Replace placeholders with actual data
        nodes_data = []
        for node in self.graph.nodes():
            # Get the definition for the node if available
            definition = ""
            synsets = wn.synsets(node)
            if synsets:
                definition = synsets[0].definition()

            nodes_data.append({
                'id': node,
                'label': self.graph.nodes[node].get('label', node),
                'color': self.graph.nodes[node].get('color', '#97c2fc'),
                'size': self.graph.nodes[node].get('size', 25),
                'title': f"<div style='max-width:300px;'><b>{node}</b><br/>{definition}</div>"
            })

        edges_data = []
        for edge in self.graph.edges():
            edge_label = self.graph.edges[edge].get('label', '')
            edges_data.append({
                'from': edge[0],
                'to': edge[1],
                'color': self.graph.edges[edge].get('color', '#848484'),
                'width': 2,
                'title': edge_label
            })

        network_data = json.dumps({
            "nodes": nodes_data,
            "edges": edges_data
        })

        # Replace the placeholder in the template with the actual data
        html_content = html_template.replace("REPLACE_WITH_DATA", network_data)

        # Save the HTML file
        if save_path:
            with open(save_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            return HTML(f'<iframe src="{save_path}" height="{height}" width="{width}"></iframe>')
        else:
            temp_path = "thesaurus_visualization.html"
            with open(temp_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            return HTML(f'<iframe src="{temp_path}" height="{height}" width="{width}"></iframe>')

    def visualize_plotly(self, word=None, height=600, width=900):
        """
        Create an interactive visualization using Plotly.

        Args:
            word (str, optional): Word to visualize. If None, uses the existing graph.
            height (int): Height of the visualization
            width (int): Width of the visualization

        Returns:
            plotly.graph_objects.Figure: Plotly figure object
        """
        if word:
            self.build_graph_for_word(word)

        if not self.graph.nodes():
            raise ValueError("Graph is empty. Please build a graph first.")

        # Create a layout for the graph
        pos = nx.spring_layout(self.graph, seed=42)

        # Create edge traces
        edge_traces = []

        for edge in self.graph.edges():
            x0, y0 = pos[edge[0]]
            x1, y1 = pos[edge[1]]

            edge_color = self.graph.edges[edge].get('color', 'gray')
            edge_label = self.graph.edges[edge].get('label', '')

            edge_trace = go.Scatter(
                x=[x0, x1, None],
                y=[y0, y1, None],
                line=dict(width=1.5, color=edge_color),
                hoverinfo='none',
                mode='lines',
                name=edge_label
            )

            edge_traces.append(edge_trace)

        # Create node trace
        node_trace = go.Scatter(
            x=[pos[node][0] for node in self.graph.nodes()],
            y=[pos[node][1] for node in self.graph.nodes()],
            mode='markers+text',
            text=[node for node in self.graph.nodes()],
            textposition='top center',
            hoverinfo='text',
            marker=dict(
                showscale=False,
                color=[self.graph.nodes[node].get('color', 'blue') for node in self.graph.nodes()],
                size=[self.graph.nodes[node].get('size', 15) for node in self.graph.nodes()],
                line=dict(width=2, color='white')
            )
        )

        # Create figure
        fig = go.Figure(
            data=edge_traces + [node_trace],
            layout=go.Layout(
                title=f'Visual Thesaurus for "{word}"' if word else 'Visual Thesaurus',
                showlegend=False,
                hovermode='closest',
                margin=dict(b=20, l=5, r=5, t=40),
                xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
                yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
                height=height,
                width=width
            )
        )

        return fig

    def create_web_visualization(self, word, output_dir='web_visualizations'):
        """
        Create a standalone HTML visualization for web display.

        Args:
            word (str): Word to visualize
            output_dir (str): Directory to save the visualization

        Returns:
            str: Path to the generated HTML file
        """
        # Create output directory if it doesn't exist
        os.makedirs(output_dir, exist_ok=True)

        # Build the graph
        self.build_graph_for_word(word)

        # Create the visualization
        output_path = os.path.join(output_dir, f'{word}_thesaurus.html')
        self.visualize_interactive(save_path=output_path)

        return output_path

# Example usage
if __name__ == "__main__":
    # Create a visual thesaurus
    visual_thesaurus = VisualThesaurus()

    # Visualize a word
    word = "happy"
    visual_thesaurus.build_graph_for_word(word)

    # Create and display visualizations
    visual_thesaurus.visualize_matplotlib(save_path=f"{word}_thesaurus.png")
    visual_thesaurus.visualize_interactive(save_path=f"{word}_thesaurus.html")

    print(f"Visualizations created for '{word}'")
